"""add daily message limit fields to user

Revision ID: 082fed19d848
Revises: 92f10f928f67
Create Date: 2026-09-05 16:56:27.500119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '082fed19d848'
down_revision: Union[str, Sequence[str], None] = '92f10f928f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_message_counter', sa.Integer(), nullable=False, server_default='0'))
    op.drop_column('user', 'daily_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('user', 'daily_message_counter')
    # ### end Alembic commands ###
