"""add title, last_message_at, message_count to chatsession

Revision ID: 0db27fa26920
Revises: ee5b8cfd405f
Create Date: 2026-08-31 18:34:47.624000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0db27fa26920'
down_revision: Union[str, Sequence[str], None] = 'ee5b8cfd405f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatsession', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('chatsession', sa.Column('last_message_at', sa.DateTime(), nullable=True))
    op.add_column('chatsession', sa.Column('message_count', sa.Integer(), nullable=True))
    # Backfill existing rows before enforcing NOT NULL: last activity defaults
    # to when the session was created, count defaults to 0 (unknown history).
    op.execute('UPDATE chatsession SET last_message_at = created_at WHERE last_message_at IS NULL')
    op.execute('UPDATE chatsession SET message_count = 0 WHERE message_count IS NULL')
    op.alter_column('chatsession', 'last_message_at', nullable=False)
    op.alter_column('chatsession', 'message_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatsession', 'message_count')
    op.drop_column('chatsession', 'last_message_at')
    op.drop_column('chatsession', 'title')
    # ### end Alembic commands ###
