"""Added accession number in Fin Statement and FilingSection

Revision ID: 21b0ca27ec36
Revises: 805317455698
Create Date: 2026-08-20 14:48:44.140954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b0ca27ec36'
down_revision: Union[str, Sequence[str], None] = '805317455698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filingsection', sa.Column('accession_number', sa.Integer(), nullable=False))
    op.add_column('filingsection', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'filingsection', 'stock', ['stock_id'], ['id'])
    op.add_column('financials', sa.Column('accession_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financials', 'accession_number')
    op.drop_constraint(None, 'filingsection', type_='foreignkey')
    op.drop_column('filingsection', 'created_at')
    op.drop_column('filingsection', 'accession_number')
    # ### end Alembic commands ###
