"""add financial table

Revision ID: 25effe64ef78
Revises: fc7df832443d
Create Date: 2026-08-11 18:26:49.916856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25effe64ef78'
down_revision: Union[str, Sequence[str], None] = 'fc7df832443d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financialline', sa.Column('standard_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('financialline', sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financialline', 'unit')
    op.drop_column('financialline', 'standard_label')
    # ### end Alembic commands ###
