"""Added FilingSection table

Revision ID: 805317455698
Revises: 12544a26b82a
Create Date: 2026-08-19 21:57:02.117254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '805317455698'
down_revision: Union[str, Sequence[str], None] = '12544a26b82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filingsection',
    sa.Column('stock_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sa.Enum('BUSINESS', 'MDA', 'RISKS', name='filingsectiontypes'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('stock_id', 'section')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('filingsection')
    # ### end Alembic commands ###
